# Generated by Django 5.0.3 on 2024-06-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0002_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_staff',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
